name: PR Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  create-changelog:
    name: Create Changelog
    if: github.event.action == 'opened' && startsWith(github.head_ref, 'release/')
    runs-on: [self-hosted, vmslave]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ORG_CORE_GITHUB_PAT }}
      - name: Changelog
        uses: saadmk11/changelog-ci@v1.0.0
        env:
          GITHUB_TOKEN: ${{secrets.ORG_CORE_GITHUB_PAT}}
        with:
          changelog_filename: .github/CHANGELOG.md
          config_file: .github/changelog-config.json
